#!/usr/bin/sh

if ! command -v notify-send >/dev/null || ! command -v pactl >/dev/null; then
    echo "notify-send or pactl is not installed"
    exit 0
fi

export LANG=C.UTF-8 LC_ALL=C.UTF-8

DEFAULT_STEP=5
LIMIT=${LIMIT:-100}

DEVICE="sink"
TARGET="@DEFAULT_SINK@"

clamp() {
    if [ "$1" -lt 0 ]; then
        echo 0
    elif [ "$1" -gt "$LIMIT" ]; then
        echo "$LIMIT"
    else
        echo "$1"
    fi
}

get_volume() {
    if [ "$DEVICE" = "source" ]; then
        ret=$(pactl get-source-volume "$TARGET")
    else
        ret=$(pactl get-sink-volume "$TARGET")
    fi

    ret=${ret%%%*}
    ret=${ret##* }
    echo "$ret"
}

is_muted() {
    if [ "$DEVICE" = "source" ]; then
        pactl get-source-mute "$TARGET" | grep -q yes
    else
        pactl get-sink-mute "$TARGET" | grep -q yes
    fi
}

CHANGE=0
VOLUME=-1

while [ $# -gt 0 ]; do
    case "$1" in
        --source)
            DEVICE="source"
            TARGET="@DEFAULT_SOURCE@"
            ;;
        --sink)
            DEVICE="sink"
            TARGET="@DEFAULT_SINK@"
            ;;
        -l|--limit)
            LIMIT="$2"
            shift
            ;;
        --set-volume)
            VOLUME="$2"
            shift
            ;;
        -i|--increase)
            CHANGE="${2:-$DEFAULT_STEP}"
            shift
            ;;
        -d|--decrease)
            CHANGE="-${
                2:-$DEFAULT_STEP
            }"
            shift
            ;;
        *)
            break
            ;;
    esac
    shift
done

if [ "$CHANGE" -ne 0 ]; then
    VOLUME=$(get_volume)
    VOLUME=$((VOLUME + CHANGE))

    if [ "$DEVICE" = "source" ]; then
        pactl set-source-volume "$TARGET" "$(clamp "$VOLUME")%"
    else
        pactl set-sink-volume "$TARGET" "$(clamp "$VOLUME")%"
    fi
elif [ "$VOLUME" -ge 0 ]; then
    if [ "$DEVICE" = "source" ]; then
        pactl set-source-volume "$TARGET" "$(clamp "$VOLUME")%"
    else
        pactl set-sink-volume "$TARGET" "$(clamp "$VOLUME")%"
    fi
fi

VOLUME=$(get_volume)

if is_muted; then
    VOLUME=0
    if [ "$DEVICE" = "source" ]; then
        TEXT="[microphone: muted]"
    else
        TEXT="[volume: muted]"
    fi
else
    if [ "$DEVICE" = "source" ]; then
        TEXT="[microphone: ${VOLUME}%]"
    else
        TEXT="[volume: ${VOLUME}%]"
    fi
fi

notify-send \
    --app-name=sway \
    --expire-time=800 \
    --hint string:x-canonical-private-synchronous:volume \
    --hint "int:value:$VOLUME" \
    --transient \
    "$TEXT"
