#!/bin/bash

STATE="/tmp/zenmode"

if [ -f "$STATE" ]; then
    #swaymsg "reload"
    swaymsg '[app_id="foot"] floating disable'
    swaymsg 'bar mode toggle'
    # idk how to restore the wallpaper so hardcoding it for now
    swaymsg 'output * bg ~/.dotfiles/wallpaper/rosepine-hi.jpg fill'
    swaymsg '[app_id="foot"] border pixel 2px'
    rm "$STATE"
else
    touch "$STATE"
    swaymsg '[app_id="foot"] floating enable; resize set 1920 1450; move position 320 10'
    swaymsg '[app_id="foot"] border none'
    swaymsg 'output * bg #000000 solid_color'
    swaymsg 'bar mode toggle'
fi
