- name: Install cankurttekin's packages
  hosts: localhost
  become: yes  # use sudo

  vars:
    packages_file: packages

  tasks:
    - name: Read package list
      ansible.builtin.slurp:
        src: "{{ packages_file }}"
      register: package_data

    - name: Set fact for package list
      ansible.builtin.set_fact:
        packages: "{{ package_data['content'] | b64decode | split('\n') | reject('equalto', '') | list }}"

    - name: Detect distro
      ansible.builtin.debug:
        msg: "Detected OS family: {{ ansible_facts.os_family }}"

    - name: Install packages on Debian
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      when: ansible_facts.os_family == "Debian"

    - name: Install packages on Fedora/RHEL
      ansible.builtin.dnf:
        name: "{{ packages }}"
        state: present
      when: ansible_facts.os_family == "RedHat"

