# -*- conf -*-
title=terminal

font=BlexMonoNerdFont:style=Regular:size=25
font-bold=BlexMonoNerdFont:style=Bold:size=25
font-italic=BlexMonoNerdFont:style:Italic:size=25

[environment]
TERM_PROGRAM=foot

[colors-light]
alpha=0.84
[colors-dark]
alpha=0.84

[main]
#include=/usr/share/foot/themes/rose-pine
include=~/.config/foot/rose-pine.ini

[url]
# Ctrl-Shift-O
launch=xdg-open ${url}
label-letters=sadfjklewcmpgh
osc8-underline=url-mode
regex=(((https?://|mailto:|ftp://|file:|ssh:|ssh://|git://|tel:|magnet:|ipfs://|ipns://|gemini://|gopher://|news:)|www\.)([0-9a-zA-Z:/?#@!$&*+,;=.~_%^\-]+|\([]\["0-9a-zA-Z:/?#@!$&'*+,;=.~_%^\-]*\)|\[[\(\)"0-9a-zA-Z:/?#@!$&'*+,;=.~_%^\-]*\]|"[]\[\(\)0-9a-zA-Z:/?#@!$&'*+,;=.~_%^\-]*"|'[]\[\(\)0-9a-zA-Z:/?#@!$&*+,;=.~_%^\-]*')+([0-9a-zA-Z/#@$&*+=~_%^\-]|\([]\["0-9a-zA-Z:/?#@!$&'*+,;=.~_%^\-]*\)|\[[\(\)"0-9a-zA-Z:/?#@!$&'*+,;=.~_%^\-]*\]|"[]\[\(\)0-9a-zA-Z:/?#@!$&'*+,;=.~_%^\-]*"|'[]\[\(\)0-9a-zA-Z:/?#@!$&*+,;=.~_%^\-]*'))

[mouse]
hide-when-typing=yes

[desktop-notifications]
command=notify-send -a ${app-id} -i ${app-id} ${title} ${body}
