## 2in1 laptop specific settings
# auto rotate 
#exec ~/.config/sway/scripts/auto-rotate &
bindswitch tablet:on exec ~/.config/sway/scripts/auto-rotate &
bindswitch tablet:off exec pkill auto-rotate

# on screen keyboard
# Requires: wvkbd
#bindswitch tablet:on exec wvkbd -L 250 &
#bindswitch tablet:off exec pkill -x wvkbd

#bindswitch lid:off exec swaymsg output eDP-1 disable
#bindswitch lid:on exec swaymsg output eDP-1 enable
