# Status Bar:`man 5 sway-bar`
#
#bindsym $mod+Shift+q exec "swaymsg bar mode toggle"
#bindsym $mod+Shift+q exec \
#  [ "$(swaymsg -t get_bar_config bar-0 | jq -r ".mode")" = "dock" ] \
#  && swaymsg bar mode invisible \
#  || swaymsg bar mode dock
#
bindsym $mod+Shift+q exec killall -SIGUSR1 waybar

#bar {
#    status_command ~/.config/sway/scripts/status.sh
#    font "Liberation Mono 14"
#    height 20 
#}
  
# `man 5 waybar`
# Requires: waybar

bar {
    swaybar_command waybar
}
