#output * bg #000000 solid_color
#output * bg ~/Pictures/Wallpapers/ fit

# Requires:     brightnessctl
# Recommends:   libnotify
set $brightness_notifier command -v notify-send >/dev/null && \
    VALUE=$(brightnessctl --percentage get) && \
    notify-send -e \
    -h string:x-canonical-private-synchronous:brightness \
    -h int:value:$VALUE \
    -t 800 \
    "[brightness $VALUE]"

# brightness
bindsym XF86MonBrightnessUp exec brightnessctl set +5% && $brightness_notifier
bindsym XF86MonBrightnessDown exec brightnessctl set 5%- && $brightness_notifier 

# rotate display manually
bindsym $mod+Shift+r exec ~/.config/sway/scripts/rotate-display.sh 

# toggle internal(laptop) display manually
bindsym --locked $mod+m output "eDP-1" toggle

# wallpaper picker
bindsym $mod+p exec ~/.config/sway/scripts/wallpaper-picker.sh

## dock
# toggle internal display and wifi with lid state
# disabling wifi because assuming i will always be docked if lid is off
bindswitch --reload --locked lid:on exec sh -c 'swaymsg output eDP-1 disable; wifi off'
bindswitch --reload --locked lid:off exec sh -c 'swaymsg output eDP-1 enable; wifi on'

# external display-dock
# TODO: make output name dynamic and use max res and refresh rate mode automatically if possible
output "DP-3" {
    mode 2560x1440@100Hz
        scale 1
}
