# Requires: grim, slurp, wl-clipboard, grimshot
bindsym {
    # Fullscreen
    Print exec grim - | tee ~/Pictures/Screenshots/screenshot-$(date +%s).png | wl-copy -t image/png
    # Area
    Shift+Print exec grim -g "$(slurp)" - | tee ~/Pictures/Screenshots/screenshot-$(date +%s).png | wl-copy -t image/png
    # Active window
    Alt+Print exec grimshot save active - | tee ~/Pictures/Screenshots/screenshot-$(date +%s).png | wl-copy -t image/png
    # Color picker
    $mod+Shift+p exec grim -g "$(slurp -p)" -t ppm - | convert - -format '%[pixel:p{0,0}]' txt:- | tail -n 1 | cut -d ' ' -f 4 | wl-copy -n
}
