# floating window on pip
for_window [title="Picture-in-Picture"] floating enable
for_window [title="Calculator"] floating enable
for_window [title="imv"] floating enable
for_window [title="mpv"] floating enable

# firefox wayland screensharing indicator
for_window [app_id="firefox" title="Firefox — Sharing Indicator"] {
    floating enable
}

for_window [app_id="thunar" title="^Rename"] floating enable
#for_window [app_id="thunar" window_type="dialog"] floating enable

# apply mark browser windows
#for_window [class="Chromium-browser"] mark Browser
#for_window [class="Brave-browser"] mark Browser
#for_window [class="firefox"]  mark Browser
#for_window [app_id="Chromium-browser"] mark Browser
#for_window [app_id="brave-browser"] mark Browser
#for_window [app_id="firefox"] mark Browser
#for_window [app_id="app.zen_browser.zen"] mark Browser

# inhibit scrensaver for fullscreen browser windows
#for_window [con_mark="Browser"] {
#    inhibit_idle fullscreen
#}

#for_window [app_id="librewolf"] floating enable

# ai chat window private
#for_window [app_id="librewolf" title="ChatGPT.*Private"] mark chatgpt
#for_window [con_mark="chatgpt"] move scratchpad
#for_window [con_mark="chatgpt"] floating enable
#bindsym $mod+o [con_mark="chatgpt"] scratchpad show

# ai chat window
#for_window [app_id="librewolf" title="ChatGPT"] mark chatgpt
#for_window [con_mark="chatgpt"] move scratchpad
#for_window [con_mark="chatgpt"] floating enable
#bindsym $mod+o [con_mark="chatgpt"] scratchpad show

# youtube music
#for_window [app_id="librewolf" title="YouTube Music"] mark music
#for_window [con_mark="music"] move scratchpad
#for_window [con_mark="music"] floating enable
#bindsym $mod+m [con_mark="music"] scratchpad show
#

# on screen keypress display
for_window [app_id="showmethekey-gtk"] floating enable, border none, resize set width 500 height 60, move position 2060 1300, sticky enable, focus disable
