## floating windows
for_window [title="Picture-in-Picture"] floating enable
for_window [title="Calculator"] floating enable
for_window [title="imv"] floating enable
for_window [title="mpv"] floating enable
for_window [app_id="librewolf"] floating enable

# browser wayland screensharing indicator
for_window [app_id="firefox" title="Firefox — Sharing Indicator"] floating enable
for_window [app_id="librewolf" title="LibreWolf — Sharing Indicator"] floating enable

for_window [app_id="thunar" title="^Rename"] floating enable
#for_window [app_id="thunar" window_type="dialog"] floating enable

# on screen keypress display
for_window [app_id="showmethekey-gtk"] floating enable, border none, resize set width 500 height 60, move position 2060 1300, sticky enable, focus disable

# apply mark browser windows
for_window [class="firefox"] mark Browser
for_window [app_id="firefox"] mark Browser
for_window [class="librewolf"] mark Browser
for_window [app_id="librewolf"] mark Browser
#for_window [class="Chromium-browser"] mark Browser
#for_window [app_id="Chromium-browser"] mark Browser

# inhibit scrensaver for fullscreen browser windows
#for_window [con_mark="Browser"] { inhibit_idle fullscreen }
